### ISSUE TITLE
I have problem in starting the projects

### ISSUE THREAD

**Issue by amrosdevops** [thangchung/practical-dapr#26]
I used command **tye Run**

I have created google API
![image](https://user-images.githubusercontent.com/64208353/85006126-681f1400-b162-11ea-9cba-024f4bdc8067.png)

![image](https://user-images.githubusercontent.com/64208353/85006437-cf3cc880-b162-11ea-9a21-6a40e4ac2118.png)

but still I couldn't be granted to the projects

![Dashboard](https://user-images.githubusercontent.com/64208353/85005880-0f4f7b80-b162-11ea-9e82-ef67d92a17b8.PNG)

Any one can help what is the problem please. Thanks

**Comment by kimcuhoang** [comment]
None of your services along with sidecars could be started. That was an issue of tye 0.2 while working with dapr. I believe that has been fixed in [tye 0.3](https://github.com/dotnet/tye/releases/tag/release%2F0.3), could you try?

**Comment by KaiWalter** [comment]
@amrosdevops can you please check whether the issue maybe related to https://github.com/dotnet/tye/issues/555

**Comment by kimcuhoang** [comment]
@amrosdevops If it is a case that @KaiWalter mentioned, you just simply copy the `pubsub.yaml` and `statestore.yaml` to the path `%UserProfile%\.dapr\components`

**Comment by amrosdevops** [comment]
I have problem in Kestrel extension 

**var ports = config.GetValue<string>("PORT").Split(";");**


System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=N8T.Infrastructure
  StackTrace:
   at N8T.Infrastructure.Kestrel.Extensions.ListenHttpAndGrpcProtocols(KestrelServerOptions options, IConfiguration config) in D:\Microservices\practical-dapr\src\BuildingBlocks\N8T.Infrastructure\Kestrel\Extensions.cs:line 20
   at CoolStore.InventoryApi.Program.<>c__DisplayClass0_0.<Main>b__3(KestrelServerOptions o) in D:\Microservices\practical-dapr\src\Inventory\CoolStore.InventoryApi\Program.cs:line 40
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

**Comment by amrosdevops** [comment]
I found the problem of PORT in the previous issue 
it was missing "port": "5015;15015"
in the inventoryApi/appsettings.json
